'\" t
.\"     Title: mx2000drv
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 02/19/2015
.\"    Manual: mx2000drv Manual
.\"    Source: mx2000drv 0.0.1
.\"  Language: English
.\"
.TH "MX2000DRV" "1" "02/19/2015" "mx2000drv 0\&.0\&.1" "mx2000drv Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mx2000drv \- MX 2000II Mouse Driver
.SH "SYNOPSIS"
.sp
\fBmx2000drv\fR [\fIOPTIONS\fR] \fICOMMAND\fR [\fIARGUMENTS\fR]
.SH "DESCRIPTION"
.sp
\fBmx2000drv\fR is a configuration driver for the Perixx MX\-2000 II Gaming Mouse\&. It allows the user to change mouse settings, button mappings, and macros\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Show syntax help and exit\&.
.RE
.PP
\fB\-p, \-\-profile\fR=\fIPROFILE\fR
.RS 4
Target the active mouse profile,
\fIPROFILE\fR, an integer between 1\-4, inclusive\&. This option is only used for the
\fBGET\fR
and
\fBSET\fR
commands, and ignored for the
\fBprofile\fR
setting inside those commands\&. If not provided, the current active profile is assumed\&.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Print extra debug information\&.
.RE
.PP
\fB\-V, \-\-version\fR
.RS 4
Print driver version and exit\&.
.RE
.SH "COMMANDS"
.SS "Configuration Commands"
.sp
inspecting or changing mouse profile settings\&. Provide all arguments to change a setting to be that value\&. Leave off the final optional argument to retrieve the current value of that setting\&.
.sp
These commands require the \fB\-p\fR option when used with any command except \fBprofile\fR\&.
.PP
\fBprofile\fR [\fIPROFILE\fR]
.RS 4
The active mouse profile, an integer 1\-4\&. The
\fB\-p\fR
option is ignored for this setting\&.
.RE
.PP
\fBbutton\fR \fINUM\fR [\fIASSIGNMENT\fR]
.RS 4
Map the specified button number to perform
\fIASSIGNMENT\fR
when clicked\&. See
\fBButton Numbers\fR
for the assignment of mouse buttons to numbers\&.
.RE
.PP
\fBmacro\fR \fINUM\fR [\fISEQUENCE\fR]
.RS 4
Map button to perform key
\fISEQUENCE\fR
when clicked\&. See
\fBButton Numbers\fR
for the assignment of mouse buttons to numbers\&.
.RE
.PP
\fBcolor\fR [\fIRGB\fR]
.RS 4
Mouse backlight color as 6\-character hexadecimal\&. Mostly\&. When breathe is enabled, each pair of hex characters also controls the fade cycle period of each LED color\&. So mixed values will end up with a bit of a color cycle between them\&. Compare 00FFFF with 0084FF
.RE
.PP
\fBbreathe\fR [\fION\fR|\fIOFF\fR]
.RS 4
Whether the mouse LEDs fade and pulse over time
.RE
.PP
\fBcycle\fR [\fION\fR|\fIOFF\fR]
.RS 4
Cycle through the RGB combinations, including intermediates (yellow, cyan, magenta), only for the LEDs enabled by
\fBcolor\fR\&. So FFFFFF will cycle through all colors and intermediates\&. 00FFFF will not show red, or magenta, but will show all others\&.
.RE
.PP
\fBlit\fR [\fITIME\fR]
.RS 4
Number of seconds the backlight is steady on when
\fBbreathe\fR
is enabled\&. Min: 0, Max: 15
.RE
.PP
\fBdark\fR [\fITIME\fR]
.RS 4
Number of seconds the backlight is off when
\fBbreathe\fR
is enabled\&. Min: 0, Max: 15
.RE
.PP
\fBpulse\fR [\fITIME\fR]
.RS 4
Number of seconds the backlight takes to transition from lit to dark, when
\fBbreathe\fR
is enabled\&. Min: 0, Max: 63
.RE
.PP
\fBstandby\fR [\fITIME\fR]
.RS 4
Enable backlight
\fITIME\fR
seconds after standby mode has come on\&. Min: 0, Max: 63
.RE
.PP
\fBbacklight\fR [\fION\fR|\fIOFF\fR]
.RS 4
Enable or disable the backlight mouse LEDs
.RE
.PP
\fBsensitivity\fR \fIX\fR|\fIY\fR [\fIVALUE\fR]
.RS 4
The pointer sensitivity, a value between \-5 and 5, inclusive\&.
.RE
.PP
\fBaccel\fR [\fISPEED\fR]
.RS 4
The mouse acceleration in milliseconds\&. Min: 0, Max: 255\&.
.RE
.PP
\fBdpi\fR \fIPRESET\fR [\fIVALUE\fR]
.RS 4
\fIPRESET\fR
must be a number 1\-4\&.
\fIVALUE\fR
must be between 100 and 5600 in increments of 100
.RE
.PP
\fBpoll\fR [\fIRATE\fR]
.RS 4
Mouse polling rate in Hz: 125, 250, 500, 1000
.RE
.SS "RESET"
.sp
Resets all mouse configurations, settings, macros, and profiles to factory default\&. Similar to a recovery mode\&.
.SS "DUMP|LOAD"
.sp
Save or load the entire mouse configuration including all settings, macros, and profiles to or from a \fIFILE\fR\&. \fB\-\fR may be provided in place of a file name for stdin/stdout\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBGeneral Syntax\fR
.RS 4
.sp
dump \fIFILE\fR
.sp
load \fIFILE\fR
.RE
.SH "BUTTON NUMBERS"
.PP
\fB1\fR \fILeft Click\fR
.RS 4
The primary mouse button, on the left side of the scroll wheel, along the DPI lights\&.
.RE
.PP
\fB2\fR \fIRight Click\fR
.RS 4
The secondary mouse button, on the right side of the scroll wheel\&.
.RE
.PP
\fB3\fR \fIScroll Wheel\fR
.RS 4
When the scroll wheel is pressed down like a button\&.
.RE
.PP
\fB4\fR \fIForward Thumb\fR
.RS 4
On the left side of the mouse, this is part of the upper pair of buttons next to each other\&. This button is the one closer to the
\fBfront\fR
of the mouse\&.
.RE
.PP
\fB5\fR \fIBackward Thumb\fR
.RS 4
On the left side of the mouse, this is part of the upper pair of buttons next to each other\&. This button is the one closer to the
\fBback\fR
of the mouse\&.
.RE
.PP
\fB6\fR \fIUp\fR
.RS 4
Directly behind the scroll wheel is a pair of buttons\&. This is the one closer to the wheel, pointing towards the
\fBfront\fR
of the mouse\&.
.RE
.PP
\fB7\fR \fIDown\fR
.RS 4
Directly behind the scroll wheel is a pair of buttons\&. This is the one farther from the wheel, pointing towards the
\fBback\fR
of the mouse\&.
.RE
.PP
\fB8\fR \fILower Thumb\fR
.RS 4
On the left side of the mouse, this button is the lowest of the three\&. It is the closest to the 4 green LEDs indicating DPI selection, towards the front of the mouse\&.
.RE
.SH "EXAMPLE"
.sp
Change the active mouse profile to 3
.sp
\fBmx2000drv profile 3\fR
.sp
Change profile 1 backlight color to blue
.sp
\fBmx2000drv \-p 1 color 0000ff\fR
.sp
Get the current profile\(cqs acceleration value
.sp
\fBmx2000drv accel\fR
.sp
Save current mouse configuration to file
.sp
\fBmx2000drv dump mem\&.bin\fR
.SH "AUTHORS"
.sp
Dan Panzarella <alsoelp@gmail\&.com>
