'\" t
.\"     Title: mx2000drv
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/27/2015
.\"    Manual: mx2000drv Manual
.\"    Source: mx2000drv 0.0.1
.\"  Language: English
.\"
.TH "MX2000DRV" "1" "01/27/2015" "mx2000drv 0\&.0\&.1" "mx2000drv Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mx2000drv \- MX 2000II Mouse Driver
.SH "SYNOPSIS"
.sp
\fBmx2000drv\fR [\fIOPTIONS\fR] \fICOMMAND\fR [\fIARGUMENTS\fR]
.SH "DESCRIPTION"
.sp
\fBmx2000drv\fR is a configuration driver for the Perixx MX\-2000 II Gaming Mouse\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Show syntax help and exit\&.
.RE
.PP
\fB\-p, \-\-profile\fR=\fIPROFILE\fR
.RS 4
Target the active mouse profile,
\fIPROFILE\fR, an integer between 1\-4, inclusive\&. This option is only used for the
\fBGET\fR
and
\fBSET\fR
commands, and ignored for the
\fBprofile\fR
setting inside those commands\&. If not provided, the current active profile is assumed\&.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Print extra debug information\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print driver version and exit\&.
.RE
.SH "COMMANDS"
.SS "SET|GET"
.sp
inspecting or changing mouse profile settings\&.
.sp
These commands require the \fB\-p\fR flag when used with any setting except \fBprofile\fR\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBGeneral Syntax\fR
.RS 4
.sp
get \fISETTING\fR
.sp
set \fISETTING\fR \fIVALUE\fR
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBSettings\fR
.RS 4
.PP
\fBprofile\fR [\fIPROFILE\fR]
.RS 4
The active mouse profile, an integer 1\-4\&. The
\fB\-p\fR
option is ignored for this setting\&.
.RE
.PP
\fBbutton\fR [\fIBUTTON NUM\fR] [\fIASSIGNMENT\fR]
.RS 4
Map the specified button number to perform
\fIASSIGNMENT\fR
when clicked\&.
.RE
.PP
\fBmacro\fR [\fIBUTTON NUM\fR] [\fISEQUENCE\fR]
.RS 4
Map button to perform key
\fISEQUENCE\fR
when clicked\&.
.RE
.PP
\fBcolor\fR [\fIRGB\fR]
.RS 4
Mouse backlight color as 6\-character hexadecimal
.RE
.PP
\fBbreathe\fR [\fION\fR|\fIOFF\fR]
.RS 4
Whether the mouse LEDs fade and pulse over time
.RE
.PP
\fBcycle\fR [\fION\fR|\fIOFF\fR]
.RS 4
Whether the mouse cycles through the colors red, green, blue, cyan, white, purple, yellow with each fade\&. When enabled, ignores
\fBcolor\fR
setting\&.
.RE
.PP
\fBlit\fR [\fITIME\fR]
.RS 4
Number of seconds the backlight is steady on when
\fBbreathe\fR
is enabled\&.
.RE
.PP
\fBdark\fR [\fITIME\fR]
.RS 4
Number of seconds the backlight is dim when
\fBbreathe\fR
is enabled\&.
.RE
.PP
\fBpulse\fR [\fITIME\fR]
.RS 4
Number of seconds the backlight takes to transition from lit to dark, when
\fBbreathe\fR
is enabled\&.
.RE
.PP
\fBstandby\fR [\fITIME\fR]
.RS 4
Enable backlight
\fITIME\fR
seconds after standby mode has come on\&.
.RE
.PP
\fBbacklight\fR [\fION\fR|\fIOFF\fR]
.RS 4
Enable or disable the backlight mouse LEDs
.RE
.PP
\fBsensitivity\fR [\fIX\fR|\fIY\fR] [\fIVALUE\fR]
.RS 4
The mouse
\fBsensitivity\fR
to be a value between \-5 and 5, inclusive\&. When using
\fBSET\fR, both parameters or only
\fIVALUE\fR
may be provided\&. When only
\fIVALUE\fR, both
\fIX\fR
and
\fIY\fR
will change\&. When using
\fBGET\fR,
\fIX\fR
or
\fIY\fR
must be provided\&.
.RE
.PP
\fBaccel\fR [\fISPEED\fR]
.RS 4
The mouse acceleration in milliseconds, between 2 and 255\&.
.RE
.PP
\fBdpi\fR \fIPRESET\fR [\fIVALUE\fR]
.RS 4
\fIPRESET\fR
must be a number 1\-4 and is required for both commands\&.
\fIVALUE\fR
must be between 100 and 1600 in increments of 100
.RE
.PP
\fBpoll\fR [\fIRATE\fR]
.RS 4
Mouse polling rate in Hz: 125, 250, 500, 1000
.RE
.RE
.SS "RESET"
.sp
Resets all mouse configurations, settings, macros, and profiles to factory default\&. Similar to a recovery mode\&.
.SS "DUMP|LOAD"
.sp
Save or load the entire mouse configuration including all settings, macros, and profiles to or from a \fIFILE\fR\&. If \fI\-\fR is provided instead, stdout/stdin will be used\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBGeneral Syntax\fR
.RS 4
.sp
dump \fIFILE\fR|\fI\-\fR
.sp
load \fIFILE\fR|\fI\-\fR
.RE
.SH "EXAMPLE"
.sp
Change the active mouse profile to 3
.sp
\fBmx2000drv set profile 3\fR
.sp
Change profile 1 backlight color to blue
.sp
\fBmx2000drv \-p 1 set color 0000ff\fR
.sp
Get the current profile\(cqs acceleration value
.sp
\fBmx2000drv get accel\fR
.sp
Save current mouse configuration to file
.sp
\fBmx2000drv dump mem\&.bin\fR
.SH "AUTHORS"
.sp
Dan Panzarella <alsoelp at gmail\&.com>
